### ISSUE TITLE
"premature close" while trying to upload some files

### ISSUE THREAD

**Issue by camden2005** [webtorrent/instant.io#210] opened 2019-10-24 06:50 UTC
**What version of this package are you using?**
Live site: https://instant.io/
**What operating system, Node.js, and npm version?**
Chrome, Firefox
**What happened?**
While I was trying to upload certain files to be tracked, I got "premature close" in Log. It appears that certain files will trigger ""premature close" error. Example file: https://github.com/GoogleChrome/workbox/releases/download/v4.3.1/workbox-v4.3.1.zip
**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by pgram1** [comment] 2019-11-04 11:36
Can confirm on Firefox on Android

**Comment by alxhotel** [comment] 2019-11-04 11:42
This is issue is already reported at webtorrent/webtorrent#1748.

**Comment by DeltaF1** [comment] 2020-02-02 17:58
This is still happening on https://instant.io, even after https://github.com/webtorrent/webtorrent/pull/1804 was merged.

**Comment by mayeaux** [comment] 2020-02-03 19:55
+1 still doesn't work

**Comment by dessalines** [comment] 2020-02-14 00:46
I'm getting this on FF 73.0

**Comment by spersico** [comment] 2020-03-21 01:33
Getting this on Chrome 80.0.3987.149 (Official Build) (64-bit)

**Comment by willstott101** [comment] 2020-03-21 16:48
AFAIK instant.io is built from released versions of Web torrent, and there hasn't been a release since that merge. So this won't be fixed until a new version of we torrent is released or someone applies the workaround to this repo in a PR.

**Comment by belvederef** [comment] 2020-04-06 09:29
This still happens on instant.io and also the latest webtorrent build. The problem is that, although webtorrent now relies on `end-of-stream@1.4.1`, there are other packages that rely on `end-of-stream@1.4.4` This is what I found this in my `yarn lockfile` with a standard installation of the latest build:
```
end-of-stream@1.4.1:
  version "1.4.1"
  resolved "https://registry.yarnpkg.com/end-of-stream/-/end-of-stream-1.4.1.tgz#ed29634d19baba463b6ce6b80a37213eab71ec43"
  integrity sha512-1MkrZNvWTKCaigbn+W15elq2BB/L22nqrSY5DKlo3X6+vclJm8Bb5djXJBmEX6fS3+zCh/F4VBK5Z2KxJt4s2Q==
  dependencies:
    once "^1.4.0"

end-of-stream@^1.0.0, end-of-stream@^1.1.0:
  version "1.4.4"
  resolved "https://registry.yarnpkg.com/end-of-stream/-/end-of-stream-1.4.4.tgz#5ae64a5f45057baf3626ec14da0ca5e4b2431eb0"
  integrity sha512-+uw1inIHVPQoaVuHzRyXd21icM+cnt4CzD5rW+NC1wjOUSTOs+Te7FOv7AhN7vS9x/oIyhLP5PR1H+phQAHu5Q==
  dependencies:
    once "^1.4.0" 
```

I had to change that to:
```
end-of-stream@1.4.1, end-of-stream@^1.0.0, end-of-stream@^1.1.0:
  version "1.4.1"
  resolved "https://registry.yarnpkg.com/end-of-stream/-/end-of-stream-1.4.1.tgz#ed29634d19baba463b6ce6b80a37213eab71ec43"
  integrity sha512-1MkrZNvWTKCaigbn+W15elq2BB/L22nqrSY5DKlo3X6+vclJm8Bb5djXJBmEX6fS3+zCh/F4VBK5Z2KxJt4s2Q==
  dependencies:
    once "^1.4.0"
```
All is working now. This was a nasty one introduced with the latest release I think. Not even including the right package in `package.json` solved the problem as it used to be.

**Comment by belvederef** [comment] 2020-04-06 09:39
This still happens on instant.io and also the latest webtorrent build. The problem is that, although webtorrent now relies on `end-of-stream@1.4.1`, there are other packages that rely on `end-of-stream@1.4.4`, so the package actually installed in the `node_module` folder is version `1.4.4`.
I do not know why something like that is allowed, it is extremely counterintuitive since the lockfile is not respected. 

To solve this, I had to edit my `yarn lockfile` (created automatically after a standard installation of the latest build) from this:
```
end-of-stream@1.4.1:
  version "1.4.1"
  resolved "https://registry.yarnpkg.com/end-of-stream/-/end-of-stream-1.4.1.tgz#ed29634d19baba463b6ce6b80a37213eab71ec43"
  integrity sha512-1MkrZNvWTKCaigbn+W15elq2BB/L22nqrSY5DKlo3X6+vclJm8Bb5djXJBmEX6fS3+zCh/F4VBK5Z2KxJt4s2Q==
  dependencies:
    once "^1.4.0"

end-of-stream@^1.0.0, end-of-stream@^1.1.0:
  version "1.4.4"
  resolved "https://registry.yarnpkg.com/end-of-stream/-/end-of-stream-1.4.4.tgz#5ae64a5f45057baf3626ec14da0ca5e4b2431eb0"
  integrity sha512-+uw1inIHVPQoaVuHzRyXd21icM+cnt4CzD5rW+NC1wjOUSTOs+Te7FOv7AhN7vS9x/oIyhLP5PR1H+phQAHu5Q==
  dependencies:
    once "^1.4.0" 
```

To this:
```
end-of-stream@1.4.1, end-of-stream@^1.0.0, end-of-stream@^1.1.0:
  version "1.4.1"
  resolved "https://registry.yarnpkg.com/end-of-stream/-/end-of-stream-1.4.1.tgz#ed29634d19baba463b6ce6b80a37213eab71ec43"
  integrity sha512-1MkrZNvWTKCaigbn+W15elq2BB/L22nqrSY5DKlo3X6+vclJm8Bb5djXJBmEX6fS3+zCh/F4VBK5Z2KxJt4s2Q==
  dependencies:
    once "^1.4.0"
```
Running `yarn install` now ensures the right version of the package is installed in `node_modules` and everything works. This was a nasty one introduced with the latest release I think. Not even including the right package in package.json solved the problem as it used to be.

Hold on to your lockerfile!

**Comment by Weedshaker** [comment] 2020-05-07 08:21
Can still confirm this error on FireFox 76 and Chrome Version 80.0.3987.132. While I tested it with webtorrent v0.108.1 on https://peerweb.site/ and it works. I assume it is only in the instant.io package.

**Comment by Weedshaker** [comment] 2020-05-08 20:22
I figured that it does not happen with text files... got to look deeper.

**Comment by feross** [comment] 2020-05-10 18:34
I just updated the dependency and pushed it to https://instant.io so the issue should be fixed!

**Comment by willstott101** [comment] 2020-05-12 14:55
Looks like it's fixed for me! :tada:

**Comment by feross** [comment] 2020-05-12 16:41
Great!

**Closed by feross** 2020-05-12 16:41 UTC

**Comment by belvederef** [comment] 2020-05-13 07:24
Amazing work @feross, it works great. However, I think this is only for Instant.io? There are related outstanding issue on the Webtorrent package (see https://github.com/webtorrent/webtorrent/issues/1757)
