### ISSUE TITLE
page crash on big file

### ISSUE THREAD

**Issue by Simplici** [webtorrent/instant.io#149] opened 2017-07-21 20:01 UTC
once I choose a big file 3.7GB, the page crashed.

![screen shot 2017-07-21 at 10 00 02 pm](https://user-images.githubusercontent.com/8101111/28480256-163f7294-6e60-11e7-9e15-c611c23b08d2.png)

**Comment by Ciao121** [comment] 2017-09-23 10:28
It happens to me also if I try to seed more smaller files. I think the total size is the issue

**Comment by imprecation** [comment] 2017-10-30 07:10
I think max file size is 2GB:
https://github.com/webtorrent/instant.io/blob/master/client/index.js#L216

**Comment by feross** [comment] 2018-05-03 19:38
This crash was due to a Chrome bug that is now fixed.

There's no max file size, though you need to have enough RAM to fit the file in memory (at the moment).

@imprecation The line you linked to is actually a size limit above which we won't attempt to use the Blob strategy in [`render-media`](https://github.com/feross/render-media). In other words, if the file doesn't support streaming and is bigger than 2GB then we won't attempt to display it. But the tab shouldn't crash in this case.

**Closed by feross** 2018-05-03 19:38 UTC

**Comment by dsernst** [comment] 2019-02-28 03:43
I'm still seeing this issue for a file that's 3.97 GB. Page crash exactly as shown in the OP's screenshot. Reproducible 100% of the time.

Using a file that's 1.05 GB instead, it works every time.

On the latest version of Chrome Stable (OS X), Version 72.0.3626.119 (Official Build) (64-bit). 
8 gb of RAM.

Both of the files are `.flv`, generated by the same screen recording program with the same settings. Doubtful too much metadata would've changed between the two files, aside from their length & filesize.

**Comment by feross** [comment] 2019-09-10 23:05
@dsernst Are you by chance on a 32-bit machine? These systems usually can't support a process using more than 2GB or 4GB of memory.

**Comment by dsernst** [comment] 2019-09-10 23:48
When I wrote this I was using a 2014 MacBook Pro. I believe that’s a 64bit machine.
